name: Playwright Tests
on:
  push:
    branches: [main, playwright, dev]
  pull_request:
    branches: [main, playwright, dev]

jobs:
  setup-and-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: setting up secrerts
        run: echo "${{ secrets.CERT }}"
          echo "${{ secrets.KEY }}"
          echo "${{ secrets.MONGO_URI }}"
          echo "${{ secrets.TOKEN_SECRET }}"
        working-directory: Server

      - name: Start Server
        run: |
          npm install
          node server.js &
        working-directory: Server

      - name: Start Client
        run: |
          npm i
          npm run dev &
        working-directory: Client/unseen/

      - name: Install Playwright dependencies
        run: npm ci
        working-directory: playwright

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: playwright

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: playwright

      # - name: Upload Playwright report
      #   uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: playwright/playwright-report/
      #     retention-days: 30
